---
services: docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t docker-centos-systemd .
  - docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-centos-systemd
  - docker exec --tty test-container env TERM=xterm pip --version